export const sampleEvents = [
  {
    id: 1,
    title: "Free Exhibition: We are here - A shared past, Muslims tell",
    date: "2025-07-03",
    time: "09:00 - 18:00",
    location: "Amsterdam Public Library (OBA)",
    address: "Oosterdok 143, Amsterdam",
    category: "Art & Culture",
    cost: "Free",
    description: "An exhibition exploring the shared history and stories of Muslims in Amsterdam and the Netherlands.",
    image: "/api/placeholder/400/250",
    organizer: "Amsterdam Public Library",
    source: "I amsterdam"
  },
  {
    id: 2,
    title: "Rooftop Open Mic Night",
    date: "2025-07-11",
    time: "18:00 - 22:00",
    location: "Zoku Amsterdam",
    address: "Weesperstraat 105, Amsterdam",
    category: "Music",
    cost: "Free",
    description: "Join us for an evening of music, poetry, and creative expression on our beautiful rooftop terrace.",
    image: "/api/placeholder/400/250",
    organizer: "Zoku Amsterdam",
    source: "Eventbrite"
  },
  {
    id: 3,
    title: "Community Lunch",
    date: "2025-07-09",
    time: "12:00 - 14:00",
    location: "Equals Clubhouse",
    address: "Nieuwezijds Voorburgwal 32, Amsterdam",
    category: "Community",
    cost: "Free",
    description: "A weekly community lunch where neighbors can meet, share a meal, and connect with each other.",
    image: "/api/placeholder/400/250",
    organizer: "Equals Clubhouse",
    source: "Eventbrite"
  },
  {
    id: 4,
    title: "Free exhibition in the Rijksmuseum gardens: Isamu Noguchi",
    date: "2025-07-03",
    time: "09:00 - 18:00",
    location: "Rijksmuseum",
    address: "Museumstraat 1, Amsterdam",
    category: "Art & Culture",
    cost: "Free",
    description: "Discover the outdoor sculptures of renowned artist Isamu Noguchi in the beautiful Rijksmuseum gardens.",
    image: "/api/placeholder/400/250",
    organizer: "Rijksmuseum",
    source: "I amsterdam"
  },
  {
    id: 5,
    title: "BootCamp Amsterdam",
    date: "2025-07-08",
    time: "19:00 - 20:30",
    location: "Tennis Kattenlaan",
    address: "Kattenlaan 10, Amsterdam",
    category: "Sports & Fitness",
    cost: "Free",
    description: "Free outdoor fitness bootcamp session. All fitness levels welcome. Bring your own water and towel.",
    image: "/api/placeholder/400/250",
    organizer: "BootCamp Amsterdam",
    source: "Eventbrite"
  },
  {
    id: 6,
    title: "Invisible Matters",
    date: "2025-07-03",
    time: "10:00 - 17:00",
    location: "Transnatural",
    address: "Various locations, Amsterdam",
    category: "Art & Culture",
    cost: "Free",
    description: "An exploration of the unseen nature around us through interactive installations and guided walks.",
    image: "/api/placeholder/400/250",
    organizer: "Transnatural",
    source: "I amsterdam"
  },
  {
    id: 7,
    title: "Free Karaoke Sundays",
    date: "2025-07-13",
    time: "20:00 - 23:00",
    location: "Lellebel: Queer Bar",
    address: "Utrechtsestraat 4, Amsterdam",
    category: "Entertainment",
    cost: "Free",
    description: "Sing your heart out at Amsterdam's most inclusive karaoke night. All voices and songs welcome!",
    image: "/api/placeholder/400/250",
    organizer: "Lellebel",
    source: "Eventbrite"
  },
  {
    id: 8,
    title: "ARTZUID 2025 Amsterdam Sculpture Biennale",
    date: "2025-07-03",
    time: "All day",
    location: "ARTZUID Informatiepaviljoen",
    address: "Zuiderpark, Amsterdam",
    category: "Art & Culture",
    cost: "Free",
    description: "International sculpture exhibition in Amsterdam's beautiful Zuiderpark featuring works by renowned artists.",
    image: "/api/placeholder/400/250",
    organizer: "ARTZUID",
    source: "I amsterdam"
  },
  {
    id: 9,
    title: "Join our online meditation community",
    date: "2025-07-10",
    time: "20:00 - 21:00",
    location: "Online",
    address: "Amsterdam (Online)",
    category: "Wellness",
    cost: "Free",
    description: "Weekly guided meditation session for beginners and experienced practitioners. Join from anywhere in Amsterdam.",
    image: "/api/placeholder/400/250",
    organizer: "Amsterdam Meditation Group",
    source: "Eventbrite"
  },
  {
    id: 10,
    title: "Festival Een Harp onder de Riem",
    date: "2025-07-03",
    time: "12:00 - 17:00",
    location: "Mozes en Aäronkerk",
    address: "Waterlooplein 205, Amsterdam",
    category: "Music",
    cost: "Free",
    description: "A beautiful harp festival featuring performances by local and international harpists in a historic church setting.",
    image: "/api/placeholder/400/250",
    organizer: "Mozes en Aäronkerk",
    source: "I amsterdam"
  }
];

export const categories = [
  "All",
  "Art & Culture",
  "Music",
  "Community",
  "Sports & Fitness",
  "Entertainment",
  "Wellness"
];

